/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as agentRegistrySol from "./AgentRegistry.sol";
export type { agentRegistrySol };
import type * as agentVaultSol from "./AgentVault.sol";
export type { agentVaultSol };
