/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accessControlSol from "./AccessControl.sol";
export type { accessControlSol };
import type * as iAccessControlSol from "./IAccessControl.sol";
export type { iAccessControlSol };
import type * as ownableSol from "./Ownable.sol";
export type { ownableSol };
