/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as accessControlSol from "./AccessControl.sol";
export * as iAccessControlSol from "./IAccessControl.sol";
export * as ownableSol from "./Ownable.sol";
